### ISSUE TITLE
[Question] Clarity on what Mode affects

### ISSUE THREAD

**Issue by jonahd-g** [rust-embedded-community/embedded-nal#24] opened 2020-11-12 17:19 UTC
I'd like some additional clarity on what Mode does, and how it affects the behavior of both read and write.  In a Write operation, there are 2 possible, and several branching ways of handling it.

1. Write, but device is busy and write operation is not possible
  a. return WouldBlock
  b. block (w/ optional timeout) until device is no-longer busy and write is possible
2. Write can be done and executes
  a. execute command and return early, assuming write will be successful
  b. block (w/ optional timeout) until write is complete and successful

For Read, there are more scenarios

1. Read, but no packets have been received
  a. return WouldBlock
  b. block (w/ optional timeout) until a packet arrives
2. Read and a packet is available
  a. read the packet into the buffer

Which of these decisions are fixed in the spec, and which are controlled by the Mode enum?  Note that there is no meaningful concept of "returning early" for the read operation.

**Comment by ryan-summers** [comment] 2020-11-12 17:28
It occurs to me that with the `nb::Result` assigned to the return values, the `Blocking` vs `NonBlocking` modes may largely be meaningless. We could just have all operations be non-blocking and allow the user to selectively block using `nb::block!()` calls. Additionally, `Timeout` is likely too complex for most embedded applications to implement.

Are there some use cases for specific `Mode` values in general?

**Comment by jonahd-g** [comment] 2020-11-12 18:37
I agree, we should lean on `nb` here instead. And yes, getting Timeout to work would definitely be a pain and should happen outside of the driver.

The only use-case that I like is the ability to `write` without waiting for completion.  But maybe that could be an argument on the `write` method.

**Comment by ryan-summers** [comment] 2020-11-12 18:48
@MathiasKoch Do you have any thoughts on this?

@thejpster As the original author, do you have any opinions as to how you were expecting `Mode` to be used?

**Comment by thejpster** [comment] 2020-11-12 19:01
My thoughts were simply that: sometimes you read, say, 16 bytes because you need 16 bytes and 15 bytes is no use to you. Sometimes you read 16 bytes because that's the size of your buffer and actually any number of bytes is fine. The third option is to return if the buffer is full or when the timeout expires.

**Comment by jonahd-g** [comment] 2020-11-12 19:05
I wouldn't have thought to provide the ability to read from a packet that hasn't fully arrived yet, is that even useful?  Maybe that could be accomplished with logic like this:
```
If packet_fully_loaded {
  read_all_data_into_buffer(read_buffer)
  return available_bytes;
} else if available_bytes > read_buffer.size {
  read_partial_packet_into_buffer(read_buffer, read_buffer.size);
  return read_buffer.size;
} else {
  return WouldBlock
}
```

In English:
> read() will return when the packet has completely loaded, or when the provided buffer is full

This would allow you to read a smaller portion of a packet early if you only need part of it, simply based on the size of the buffer.  And there would be no need for a Mode.

**Comment by MathiasKoch** [comment] 2020-11-12 19:15
TBH I don't really use mode in my implementations.. My implementations are all buffer based, so the read is actually just a copy from one buffer to another, thus the blocking/non-blocking is kind of a moot point.

**Comment by ryan-summers** [comment] 2020-11-13 06:28
> TBH I don't really use mode in my implementations.. My implementations are all buffer based, so the read is actually just a copy from one buffer to another, thus the blocking/non-blocking is kind of a moot point.

This is basically how I've done it as well. I've never found a logical implementation for `Mode` because the underlying network stack is usually inherently blocking/nonblocking by design, so it's not usually configurable (e.g. smoltcp or the w5500)

**Comment by ryan-summers** [comment] 2020-11-13 06:30
> ...
> 
> This would allow you to read a smaller portion of a packet early if you only need part of it, simply based on the size of the buffer. And there would be no need for a Mode.

I think we can expect that this kind of buffering logic would live inside of an implementee of the `embedded-nal`, but shouldn't necessarily be part of the abstract interface, as that would force us to buffer all implementations, which isn't necessarily desirable (we may want zero-copy implementations).

**Comment by jonahd-g** [comment] 2020-11-13 22:21
> I think we can expect that this kind of buffering logic would live inside of an implementee of the embedded-nal, but shouldn't necessarily be part of the abstract interface, as that would force us to buffer all implementations, which isn't necessarily desirable (we may want zero-copy implementations).

I can't tell whether you're agreeing or disagreeing.  If you're just saying that a driver _could_ do that but doesn't necessarily have to, then we're on the same page.

**Comment by jonahd-g** [comment] 2020-11-13 22:21
> This is basically how I've done it as well. I've never found a logical implementation for Mode because the underlying network stack is usually inherently blocking/nonblocking by design, so it's not usually configurable (e.g. smoltcp or the w5500)

Does this mean that `Mode` should go away?  I think it should, personally.

**Comment by MathiasKoch** [comment] 2020-11-14 07:49
I would personally be okay, with it going away

**Comment by ryan-summers** [comment] 2020-11-14 10:40
I'm also on-board with removing the `Mode`.

**Closed as completed** 2020-11-17 08:09 UTC
